### ISSUE TITLE
mapas

### ISSUE THREAD

**Issue by kayser666** [irvingromero/Recicladora#1]
amigo una pregunta como puedo ocupar mi propia api de google maps porque lo hago y no funciona ni si quiera cuando genero una apk porque cuando la pruebo virtual funciona peroasi solo nada de nada saludos

**Comment by kayser666** [comment]
con la api que tu dejas funciona pero si la cambio no pasa nada

**Comment by kayser666** [comment]
porqu no puedo hacer funcionar mi propia api de google maps??

**Comment by irvingromero** [comment]
Tienes que generar tu propia llave con tu proyecto, puedes buscar en goole: google api console y ahi te vas a Credenciales y creas una, de ahi te vas a Biblioteca y activas Maps SDK android y Geolocation AIP y listo. Espero te ayude, Saludos
